language: node_js
node_js:
- '8'
cache: yarn
script: yarn test
before_deploy: yarn
deploy:
  provider: npm
  email: igor@kamyshev.me
  skip_cleanup: true
  api_key:
    secure: mHrs1fN63C8e0jfcdkQrWpzsMmLjFbFUYsuImuI+UdLFe9jUerAJkqAkXeAAlpd8MQXl/BDYbUfOOhl7LiYXr05YhRVX2FAlJeKkIY5JQr5uJzlN0SHi3kG/t5ZX4uLaDeVYL99s+gayLVXkumY3FTiAmpWhwV71ayyPKRrYn7E+x6sJv31nPn8WXLmbGZ7Wxn9Lz/fReiweG1yt/QccoNj4iKiYUjXRP1OXuOMl6qTWRqT47weYVzMs2mpAYuUSXrXM4sx1HpP0ZkFY8+es4FGBRWLCOA/SrGZgO53HZ3rfirOr3D5OU4pzNgO2C46O6tnxjn87n9KmtsPbbr2vo61fOYu1sQnJHLo7sWX0cZw5Uj9/j+gv9pb11hjnMWZkse/reFGOq7hzNZDwAK7zmaI5UNo7Cfjrhbk6eIsmw52wOZAtQocEESeCtOllGPDOEzew0/20zHUp6EJMZZ4BL6wY4APPbT21mBzmTWoxgSPnfZXw7c6duPdEg8RqGQjD6eyfxpBaZdmXA113l6TYy9lX7jAwGnc90XDdsqcTea54dLpDSeG0aUsEM/6pelsRS5cVQM4Y/WwoMA4nbI6jrpN0gVcY+KTTP4Jyrkuml0QinilPIIXaamVLKzEMU0guB0ShLwpI8VjiaNGyws/7hDsISAKfDW6U6zhK+ptI1Wk=
  on:
    tags: true
    repo: breadhead/detil-ts
